- training:
  name: Fundamentals of Marklogic Server
  time: 2017-01
  by: Marklogic University
  desc: Fundamentals of MarkLogic like database, forest and application services
  
- training:
  name: Administrating Marklogic Server
  time: 2017-06
  by: MarkLogic University
  desc: Three days training of Advanced administrative tasks of MarkLogic Database Server
